// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace NordKredit.BDD.Features.Deposits
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "BDD")]
    [Xunit.TraitAttribute("Category", "Deposits")]
    [Xunit.TraitAttribute("Category", "DEP-BR-002")]
    public partial class DepositAccountOpeningFeature : object, Xunit.IClassFixture<DepositAccountOpeningFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "BDD",
                "Deposits",
                "DEP-BR-002"};
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "DepositAccountOpening.feature"
#line hidden
        
        public DepositAccountOpeningFeature(DepositAccountOpeningFeature.FixtureData fixtureData, NordKredit_BDD_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Deposits", "Deposit account opening", @"    As a bank operator
    I want to open new deposit accounts with proper validation
    So that account creation complies with FSA and AML requirements

    COBOL source: CVACT01Y.cpy (ACCOUNT-RECORD), WRITE ACCOUNT-RECORD to ACCTFILE.
    Business rule: DEP-BR-002 (account opening).
    Regulations: FSA FFFS 2014:5 Ch. 3, AML 2017:11, Deposit Guarantee Directive.", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="New demand savings account has correct defaults")]
        [Xunit.TraitAttribute("FeatureTitle", "Deposit account opening")]
        [Xunit.TraitAttribute("Description", "New demand savings account has correct defaults")]
        public void NewDemandSavingsAccountHasCorrectDefaults()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("New demand savings account has correct defaults", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 16
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                            "AccountId",
                            "HolderName",
                            "ProductType",
                            "DisclosureGroupId"});
                table15.AddRow(new string[] {
                            "12345678901",
                            "ERIK SVENSSON",
                            "DemandSavings",
                            "SAVINGS01"});
#line 17
        testRunner.Given("I create a deposit account with", ((string)(null)), table15, "Given ");
#line hidden
#line 20
        testRunner.Then("the new account has status \"Active\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 21
        testRunner.And("the new account has balance 0.00", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 22
        testRunner.And("the new account has current cycle credit 0.00", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 23
        testRunner.And("the new account has current cycle debit 0.00", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 24
        testRunner.And("the new account has accrued interest 0.0000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 25
        testRunner.And("the new account has an opened date", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="New term deposit account records maturity date")]
        [Xunit.TraitAttribute("FeatureTitle", "Deposit account opening")]
        [Xunit.TraitAttribute("Description", "New term deposit account records maturity date")]
        public void NewTermDepositAccountRecordsMaturityDate()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("New term deposit account records maturity date", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 27
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                            "AccountId",
                            "HolderName",
                            "ProductType",
                            "DisclosureGroupId"});
                table16.AddRow(new string[] {
                            "99999999999",
                            "ANNA LINDQVIST",
                            "TermDeposit",
                            "TERM12M"});
#line 28
        testRunner.Given("I create a deposit account with maturity date \"2026-06-15\" and", ((string)(null)), table16, "Given ");
#line hidden
#line 31
        testRunner.Then("the new account has status \"Active\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 32
        testRunner.And("the new account has maturity date \"2026-06-15\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Account holder name supports Swedish characters")]
        [Xunit.TraitAttribute("FeatureTitle", "Deposit account opening")]
        [Xunit.TraitAttribute("Description", "Account holder name supports Swedish characters")]
        public void AccountHolderNameSupportsSwedishCharacters()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Account holder name supports Swedish characters", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 35
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                            "AccountId",
                            "HolderName",
                            "ProductType",
                            "DisclosureGroupId"});
                table17.AddRow(new string[] {
                            "55555555555",
                            "BJÖRK ÅKERSTRÖM",
                            "DemandSavings",
                            "SAVINGS01"});
#line 36
        testRunner.Given("I create a deposit account with", ((string)(null)), table17, "Given ");
#line hidden
#line 39
        testRunner.Then("the new account has holder name \"BJÖRK ÅKERSTRÖM\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                DepositAccountOpeningFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                DepositAccountOpeningFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
