// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace NordKredit.BDD.Features.Deposits
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "BDD")]
    [Xunit.TraitAttribute("Category", "Deposits")]
    [Xunit.TraitAttribute("Category", "DEP-BR-004")]
    [Xunit.TraitAttribute("Category", "DEP-BR-006")]
    public partial class DepositInterestCalculationWithTieredRatesFeature : object, Xunit.IClassFixture<DepositInterestCalculationWithTieredRatesFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "BDD",
                "Deposits",
                "DEP-BR-004",
                "DEP-BR-006"};
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "InterestCalculation.feature"
#line hidden
        
        public DepositInterestCalculationWithTieredRatesFeature(DepositInterestCalculationWithTieredRatesFeature.FixtureData fixtureData, NordKredit_BDD_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Deposits", "Deposit interest calculation with tiered rates", @"    As a bank system
    I want to calculate daily interest for deposit accounts based on product rate schedules
    So that interest accrual complies with FSA disclosure requirements

    COBOL source: Dedicated interest calculation batch program.
    Business rules: DEP-BR-004 (interest calculation and accrual), DEP-BR-006 (tiered rates).
    Regulations: FSA FFFS 2014:5 Ch. 3 & 6, Deposit Guarantee Directive, PSD2 Art. 57.", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Daily interest for flat rate product using 365-day basis")]
        [Xunit.TraitAttribute("FeatureTitle", "Deposit interest calculation with tiered rates")]
        [Xunit.TraitAttribute("Description", "Daily interest for flat rate product using 365-day basis")]
        public void DailyInterestForFlatRateProductUsing365_DayBasis()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Daily interest for flat rate product using 365-day basis", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 17
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 18
        testRunner.Given("a savings product with annual rate 0.025 and day count basis 365", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 19
        testRunner.When("I calculate daily deposit interest on balance 100000.00", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 20
        testRunner.Then("the daily interest is 6.8493", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Daily interest for flat rate product using 360-day basis")]
        [Xunit.TraitAttribute("FeatureTitle", "Deposit interest calculation with tiered rates")]
        [Xunit.TraitAttribute("Description", "Daily interest for flat rate product using 360-day basis")]
        public void DailyInterestForFlatRateProductUsing360_DayBasis()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Daily interest for flat rate product using 360-day basis", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 22
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 23
        testRunner.Given("a savings product with annual rate 0.025 and day count basis 360", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 24
        testRunner.When("I calculate daily deposit interest on balance 100000.00", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 25
        testRunner.Then("the daily interest is 6.9444", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Zero balance yields zero interest")]
        [Xunit.TraitAttribute("FeatureTitle", "Deposit interest calculation with tiered rates")]
        [Xunit.TraitAttribute("Description", "Zero balance yields zero interest")]
        public void ZeroBalanceYieldsZeroInterest()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Zero balance yields zero interest", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 27
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 28
        testRunner.Given("a savings product with annual rate 0.025 and day count basis 365", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 29
        testRunner.When("I calculate daily deposit interest on balance 0.00", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 30
        testRunner.Then("the daily interest is 0.0000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Negative balance yields zero interest")]
        [Xunit.TraitAttribute("FeatureTitle", "Deposit interest calculation with tiered rates")]
        [Xunit.TraitAttribute("Description", "Negative balance yields zero interest")]
        public void NegativeBalanceYieldsZeroInterest()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Negative balance yields zero interest", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 32
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 33
        testRunner.Given("a savings product with annual rate 0.025 and day count basis 365", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 34
        testRunner.When("I calculate daily deposit interest on balance -5000.00", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 35
        testRunner.Then("the daily interest is 0.0000", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Tiered interest when balance is within tier 1")]
        [Xunit.TraitAttribute("FeatureTitle", "Deposit interest calculation with tiered rates")]
        [Xunit.TraitAttribute("Description", "Tiered interest when balance is within tier 1")]
        public void TieredInterestWhenBalanceIsWithinTier1()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Tiered interest when balance is within tier 1", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 45
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                            "AnnualRate",
                            "Tier1Limit",
                            "Tier2Rate",
                            "Tier2Limit",
                            "Tier3Rate",
                            "DayCountBasis"});
                table19.AddRow(new string[] {
                            "0.02",
                            "50000",
                            "0.03",
                            "100000",
                            "0.04",
                            "365"});
#line 46
        testRunner.Given("a tiered savings product with", ((string)(null)), table19, "Given ");
#line hidden
#line 49
        testRunner.When("I calculate daily deposit interest on balance 30000.00", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 50
        testRunner.Then("the daily interest is 1.6438", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Tiered interest when balance spans tier 1 and tier 2")]
        [Xunit.TraitAttribute("FeatureTitle", "Deposit interest calculation with tiered rates")]
        [Xunit.TraitAttribute("Description", "Tiered interest when balance spans tier 1 and tier 2")]
        public void TieredInterestWhenBalanceSpansTier1AndTier2()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Tiered interest when balance spans tier 1 and tier 2", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 52
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                            "AnnualRate",
                            "Tier1Limit",
                            "Tier2Rate",
                            "Tier2Limit",
                            "Tier3Rate",
                            "DayCountBasis"});
                table20.AddRow(new string[] {
                            "0.02",
                            "50000",
                            "0.03",
                            "100000",
                            "0.04",
                            "365"});
#line 53
        testRunner.Given("a tiered savings product with", ((string)(null)), table20, "Given ");
#line hidden
#line 56
        testRunner.When("I calculate daily deposit interest on balance 75000.00", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 60
        testRunner.Then("the daily interest is 4.7945", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Tiered interest when balance spans all three tiers")]
        [Xunit.TraitAttribute("FeatureTitle", "Deposit interest calculation with tiered rates")]
        [Xunit.TraitAttribute("Description", "Tiered interest when balance spans all three tiers")]
        public void TieredInterestWhenBalanceSpansAllThreeTiers()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Tiered interest when balance spans all three tiers", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 62
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                            "AnnualRate",
                            "Tier1Limit",
                            "Tier2Rate",
                            "Tier2Limit",
                            "Tier3Rate",
                            "DayCountBasis"});
                table21.AddRow(new string[] {
                            "0.02",
                            "50000",
                            "0.03",
                            "100000",
                            "0.04",
                            "365"});
#line 63
        testRunner.Given("a tiered savings product with", ((string)(null)), table21, "Given ");
#line hidden
#line 66
        testRunner.When("I calculate daily deposit interest on balance 150000.00", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 71
        testRunner.Then("the daily interest is 12.3288", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                DepositInterestCalculationWithTieredRatesFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                DepositInterestCalculationWithTieredRatesFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
