// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace NordKredit.BDD.Features.Deposits
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "BDD")]
    [Xunit.TraitAttribute("Category", "Deposits")]
    [Xunit.TraitAttribute("Category", "DEP-BR-005")]
    public partial class TermDepositMaturityAndRenewalProcessingFeature : object, Xunit.IClassFixture<TermDepositMaturityAndRenewalProcessingFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "BDD",
                "Deposits",
                "DEP-BR-005"};
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "TermDepositMaturity.feature"
#line hidden
        
        public TermDepositMaturityAndRenewalProcessingFeature(TermDepositMaturityAndRenewalProcessingFeature.FixtureData fixtureData, NordKredit_BDD_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Deposits", "Term deposit maturity and renewal processing", @"    As a bank system
    I want to detect matured term deposits and process renewal instructions
    So that term deposit lifecycle complies with FSA and Deposit Guarantee Directive

    COBOL source: CVACT01Y.cpy (ACCT-EXPIRAION-DATE), CBTRN02C.cbl:414-420.
    Business rule: DEP-BR-005 (term deposit maturity and renewal processing).
    Regulations: FSA FFFS 2014:5 Ch. 3, Deposit Guarantee Directive, PSD2 Art. 57.", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Term deposit is matured when maturity date has passed")]
        [Xunit.TraitAttribute("FeatureTitle", "Term deposit maturity and renewal processing")]
        [Xunit.TraitAttribute("Description", "Term deposit is matured when maturity date has passed")]
        public void TermDepositIsMaturedWhenMaturityDateHasPassed()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Term deposit is matured when maturity date has passed", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 17
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 18
        testRunner.Given("a deposit account with maturity date \"2025-06-15\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 19
        testRunner.When("I check maturity as of \"2025-06-16\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 20
        testRunner.Then("the account is matured", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Term deposit is not matured on maturity date")]
        [Xunit.TraitAttribute("FeatureTitle", "Term deposit maturity and renewal processing")]
        [Xunit.TraitAttribute("Description", "Term deposit is not matured on maturity date")]
        public void TermDepositIsNotMaturedOnMaturityDate()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Term deposit is not matured on maturity date", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 22
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 23
        testRunner.Given("a deposit account with maturity date \"2025-06-15\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 24
        testRunner.When("I check maturity as of \"2025-06-15\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 25
        testRunner.Then("the account is not matured", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Term deposit is not matured before maturity date")]
        [Xunit.TraitAttribute("FeatureTitle", "Term deposit maturity and renewal processing")]
        [Xunit.TraitAttribute("Description", "Term deposit is not matured before maturity date")]
        public void TermDepositIsNotMaturedBeforeMaturityDate()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Term deposit is not matured before maturity date", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 27
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 28
        testRunner.Given("a deposit account with maturity date \"2025-06-15\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 29
        testRunner.When("I check maturity as of \"2025-06-14\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 30
        testRunner.Then("the account is not matured", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Demand deposit without maturity date is never matured")]
        [Xunit.TraitAttribute("FeatureTitle", "Term deposit maturity and renewal processing")]
        [Xunit.TraitAttribute("Description", "Demand deposit without maturity date is never matured")]
        public void DemandDepositWithoutMaturityDateIsNeverMatured()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Demand deposit without maturity date is never matured", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 32
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 33
        testRunner.Given("a deposit account without a maturity date", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 34
        testRunner.When("I check maturity as of \"2025-06-16\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 35
        testRunner.Then("the account is not matured", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Term deposit records renewal instruction")]
        [Xunit.TraitAttribute("FeatureTitle", "Term deposit maturity and renewal processing")]
        [Xunit.TraitAttribute("Description", "Term deposit records renewal instruction")]
        public void TermDepositRecordsRenewalInstruction()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Term deposit records renewal instruction", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 41
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                            "TermMonths",
                            "FixedRate",
                            "PrincipalAmount",
                            "RenewalInstruction",
                            "StartDate"});
                table22.AddRow(new string[] {
                            "12",
                            "0.035",
                            "100000.00",
                            "AutoRenew",
                            "2024-06-15"});
#line 42
        testRunner.Given("a term deposit for account \"12345678901\" with", ((string)(null)), table22, "Given ");
#line hidden
#line 45
        testRunner.Then("the term deposit has term months 12", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 46
        testRunner.And("the term deposit has fixed rate 0.035", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 47
        testRunner.And("the term deposit has principal amount 100000.00", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 48
        testRunner.And("the term deposit has renewal instruction \"AutoRenew\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Term deposit with payout instruction has linked account")]
        [Xunit.TraitAttribute("FeatureTitle", "Term deposit maturity and renewal processing")]
        [Xunit.TraitAttribute("Description", "Term deposit with payout instruction has linked account")]
        public void TermDepositWithPayoutInstructionHasLinkedAccount()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Term deposit with payout instruction has linked account", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 50
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
                            "TermMonths",
                            "FixedRate",
                            "PrincipalAmount",
                            "RenewalInstruction",
                            "LinkedAccountId",
                            "StartDate"});
                table23.AddRow(new string[] {
                            "6",
                            "0.028",
                            "50000.00",
                            "Payout",
                            "99999999999",
                            "2025-01-01"});
#line 51
        testRunner.Given("a term deposit for account \"12345678901\" with", ((string)(null)), table23, "Given ");
#line hidden
#line 54
        testRunner.Then("the term deposit has renewal instruction \"Payout\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 55
        testRunner.And("the term deposit has linked account ID \"99999999999\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                TermDepositMaturityAndRenewalProcessingFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                TermDepositMaturityAndRenewalProcessingFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
