// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  mainSidebar: [
    {
      type: 'category',
      label: 'Business Rules',
      link: {
        type: 'generated-index',
        title: 'Business Rules',
        description: 'Extracted business rules from COBOL source programs, organized by domain.',
      },
      items: [
        {
          type: 'category',
          label: 'Account Management',
          link: {
            type: 'generated-index',
            title: 'Account Management',
            description: 'Business rules for account lifecycle, balance management, and account operations.',
          },
          items: [{type: 'autogenerated', dirName: 'business-rules/account-management'}],
        },
        {
          type: 'category',
          label: 'Card Management',
          link: {
            type: 'generated-index',
            title: 'Card Management',
            description: 'Business rules for card issuance, activation, blocking, and card data management.',
          },
          items: [{type: 'autogenerated', dirName: 'business-rules/card-management'}],
        },
        {
          type: 'category',
          label: 'Transactions',
          link: {
            type: 'generated-index',
            title: 'Transactions',
            description: 'Business rules for payment processing, transaction validation, and settlement.',
          },
          items: [{type: 'autogenerated', dirName: 'business-rules/transactions'}],
        },
        {
          type: 'category',
          label: 'User/Security',
          link: {
            type: 'generated-index',
            title: 'User/Security',
            description: 'Business rules for authentication, authorization, and user management.',
          },
          items: [{type: 'autogenerated', dirName: 'business-rules/user-security'}],
        },
        {
          type: 'category',
          label: 'Billing',
          link: {
            type: 'generated-index',
            title: 'Billing',
            description: 'Business rules for fee calculation, interest computation, and billing cycles.',
          },
          items: [{type: 'autogenerated', dirName: 'business-rules/billing'}],
        },
        {
          type: 'category',
          label: 'Reporting',
          link: {
            type: 'generated-index',
            title: 'Reporting',
            description: 'Business rules for regulatory reports, statements, and analytics.',
          },
          items: [{type: 'autogenerated', dirName: 'business-rules/reporting'}],
        },
      ],
    },
    {
      type: 'category',
      label: 'Data Structures',
      link: {
        type: 'generated-index',
        title: 'Data Structures',
        description: 'COBOL copybook definitions and their mapped .NET equivalents.',
      },
      items: [{type: 'autogenerated', dirName: 'data-structures'}],
    },
    {
      type: 'category',
      label: 'Batch Processes',
      link: {
        type: 'generated-index',
        title: 'Batch Processes',
        description: 'JCL batch job documentation and Azure Functions migration mappings.',
      },
      items: [{type: 'autogenerated', dirName: 'batch-processes'}],
    },
    {
      type: 'category',
      label: 'Requirements',
      link: {
        type: 'generated-index',
        title: 'Requirements',
        description: 'Use cases and user stories organized by domain, derived from extracted business rules.',
      },
      items: [
        {
          type: 'category',
          label: 'Transactions',
          link: {
            type: 'generated-index',
            title: 'Transaction Requirements',
            description: 'Use cases for the transaction processing domain.',
          },
          items: [{type: 'autogenerated', dirName: 'requirements/transactions'}],
        },
      ],
    },
    {
      type: 'category',
      label: 'Regulatory Traceability',
      link: {
        type: 'generated-index',
        title: 'Regulatory Traceability',
        description: 'Traceability matrices linking business rules to FSA, PSD2, GDPR, AML/KYC, and DORA requirements.',
      },
      items: [{type: 'autogenerated', dirName: 'regulatory-traceability'}],
    },
  ],
};

export default sidebars;
