// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace NordKredit.BDD.Features.Transactions
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "BDD")]
    [Xunit.TraitAttribute("Category", "Transactions")]
    [Xunit.TraitAttribute("Category", "TRN-BR-003")]
    public partial class TransactionAddWithValidationFeature : object, Xunit.IClassFixture<TransactionAddWithValidationFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "BDD",
                "Transactions",
                "TRN-BR-003"};
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "TransactionAdd.feature"
#line hidden
        
        public TransactionAddWithValidationFeature(TransactionAddWithValidationFeature.FixtureData fixtureData, NordKredit_BDD_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Transactions", "Transaction add with validation", @"    As a bank operator
    I want to add new transactions with input validation
    So that only valid transaction data enters the system

    COBOL source: COTRN02C.cbl:106-784 (CICS transaction CT02 — add transaction).
    Business rules: TRN-BR-003 (transaction add with validation).
    Regulations: FFFS 2014:5 Ch.8 (accurate records), PSD2 Art.94 (transaction retention).", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 11
    #line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "CardNumber",
                        "AccountId",
                        "CustomerId"});
            table15.AddRow(new string[] {
                        "4000123456789012",
                        "12345678901",
                        "1001"});
#line 12
        testRunner.Given("the card cross-reference contains", ((string)(null)), table15, "Given ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Successful transaction add")]
        [Xunit.TraitAttribute("FeatureTitle", "Transaction add with validation")]
        [Xunit.TraitAttribute("Description", "Successful transaction add")]
        public void SuccessfulTransactionAdd()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Successful transaction add", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 19
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 11
    this.FeatureBackground();
#line hidden
#line 20
        testRunner.Given("the transaction ID generator will return \"TRN00000099\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                            "CardNumber",
                            "TypeCode",
                            "CategoryCode",
                            "Source",
                            "Description",
                            "Amount",
                            "OriginationDate",
                            "ProcessingDate",
                            "MerchantId",
                            "MerchantName",
                            "MerchantCity",
                            "MerchantZip",
                            "Confirm"});
                table16.AddRow(new string[] {
                            "4000123456789012",
                            "01",
                            "5010",
                            "ONLINE",
                            "GROCERY STORE",
                            "+00000125.50",
                            "2024-01-15",
                            "2024-01-16",
                            "12345",
                            "ACME FOODS AB",
                            "STOCKHOLM",
                            "11120",
                            "Y"});
#line 21
        testRunner.When("I submit a transaction add request with", ((string)(null)), table16, "When ");
#line hidden
#line 24
        testRunner.Then("the transaction add result is success", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 25
        testRunner.And("the assigned transaction ID is \"TRN00000099\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Validation failure for unknown card number")]
        [Xunit.TraitAttribute("FeatureTitle", "Transaction add with validation")]
        [Xunit.TraitAttribute("Description", "Validation failure for unknown card number")]
        public void ValidationFailureForUnknownCardNumber()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Validation failure for unknown card number", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 28
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 11
    this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                            "CardNumber",
                            "TypeCode",
                            "CategoryCode",
                            "Source",
                            "Description",
                            "Amount",
                            "OriginationDate",
                            "ProcessingDate",
                            "MerchantId",
                            "MerchantName",
                            "MerchantCity",
                            "MerchantZip",
                            "Confirm"});
                table17.AddRow(new string[] {
                            "9999999999999999",
                            "01",
                            "5010",
                            "ONLINE",
                            "GROCERY STORE",
                            "+00000125.50",
                            "2024-01-15",
                            "2024-01-16",
                            "12345",
                            "ACME FOODS AB",
                            "STOCKHOLM",
                            "11120",
                            "Y"});
#line 29
        testRunner.When("I submit a transaction add request with", ((string)(null)), table17, "When ");
#line hidden
#line 32
        testRunner.Then("the transaction add result is validation error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Confirmation required before first add")]
        [Xunit.TraitAttribute("FeatureTitle", "Transaction add with validation")]
        [Xunit.TraitAttribute("Description", "Confirmation required before first add")]
        public void ConfirmationRequiredBeforeFirstAdd()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Confirmation required before first add", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 35
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 11
    this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                            "CardNumber",
                            "TypeCode",
                            "CategoryCode",
                            "Source",
                            "Description",
                            "Amount",
                            "OriginationDate",
                            "ProcessingDate",
                            "MerchantId",
                            "MerchantName",
                            "MerchantCity",
                            "MerchantZip",
                            "Confirm"});
                table18.AddRow(new string[] {
                            "4000123456789012",
                            "01",
                            "5010",
                            "ONLINE",
                            "GROCERY STORE",
                            "+00000125.50",
                            "2024-01-15",
                            "2024-01-16",
                            "12345",
                            "ACME FOODS AB",
                            "STOCKHOLM",
                            "11120",
                            ""});
#line 36
        testRunner.When("I submit a transaction add request with", ((string)(null)), table18, "When ");
#line hidden
#line 39
        testRunner.Then("the transaction add result is confirmation required", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Duplicate transaction ID rejected")]
        [Xunit.TraitAttribute("FeatureTitle", "Transaction add with validation")]
        [Xunit.TraitAttribute("Description", "Duplicate transaction ID rejected")]
        public void DuplicateTransactionIDRejected()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Duplicate transaction ID rejected", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 42
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 11
    this.FeatureBackground();
#line hidden
#line 43
        testRunner.Given("the transaction ID generator will return \"TRN00000001\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 44
        testRunner.And("the transaction repository already contains transaction \"TRN00000001\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                            "CardNumber",
                            "TypeCode",
                            "CategoryCode",
                            "Source",
                            "Description",
                            "Amount",
                            "OriginationDate",
                            "ProcessingDate",
                            "MerchantId",
                            "MerchantName",
                            "MerchantCity",
                            "MerchantZip",
                            "Confirm"});
                table19.AddRow(new string[] {
                            "4000123456789012",
                            "01",
                            "5010",
                            "ONLINE",
                            "GROCERY STORE",
                            "+00000125.50",
                            "2024-01-15",
                            "2024-01-16",
                            "12345",
                            "ACME FOODS AB",
                            "STOCKHOLM",
                            "11120",
                            "Y"});
#line 45
        testRunner.When("I submit a transaction add request with", ((string)(null)), table19, "When ");
#line hidden
#line 48
        testRunner.Then("the transaction add result is duplicate key", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Retrieve last transaction for copy")]
        [Xunit.TraitAttribute("FeatureTitle", "Transaction add with validation")]
        [Xunit.TraitAttribute("Description", "Retrieve last transaction for copy")]
        public void RetrieveLastTransactionForCopy()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Retrieve last transaction for copy", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 51
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 11
    this.FeatureBackground();
#line hidden
#line 52
        testRunner.Given("the transaction repository contains a last transaction with ID \"TRN00000098\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 53
        testRunner.When("I request the last transaction", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 54
        testRunner.Then("the last transaction ID is \"TRN00000098\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                TransactionAddWithValidationFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                TransactionAddWithValidationFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
