// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace NordKredit.BDD.Features.Transactions
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "BDD")]
    [Xunit.TraitAttribute("Category", "Transactions")]
    [Xunit.TraitAttribute("Category", "TRN-BR-001")]
    public partial class TransactionListDisplayWithKeysetPaginationFeature : object, Xunit.IClassFixture<TransactionListDisplayWithKeysetPaginationFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "BDD",
                "Transactions",
                "TRN-BR-001"};
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "TransactionList.feature"
#line hidden
        
        public TransactionListDisplayWithKeysetPaginationFeature(TransactionListDisplayWithKeysetPaginationFeature.FixtureData fixtureData, NordKredit_BDD_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Transactions", "Transaction list display with keyset pagination", @"    As a bank operator
    I want to view a paginated list of posted transactions
    So that I can browse transaction history for audit and customer service

    COBOL source: COTRN00C.cbl:94-328 (CICS transaction CT00 — paginated transaction list).
    Business rules: TRN-BR-001 (transaction list display with pagination).
    Regulations: FFFS 2014:5 Ch.8 (operational info systems), PSD2 Art.94 (transaction history access).", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 11
    #line hidden
            TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Description",
                        "Amount",
                        "OriginationTimestamp"});
            table21.AddRow(new string[] {
                        "TRN00000001",
                        "GROCERY STORE",
                        "45.50",
                        "2024-01-15"});
            table21.AddRow(new string[] {
                        "TRN00000002",
                        "GAS STATION",
                        "62.00",
                        "2024-01-15"});
            table21.AddRow(new string[] {
                        "TRN00000003",
                        "ONLINE PURCHASE",
                        "129.99",
                        "2024-01-16"});
            table21.AddRow(new string[] {
                        "TRN00000004",
                        "RESTAURANT",
                        "38.75",
                        "2024-01-16"});
            table21.AddRow(new string[] {
                        "TRN00000005",
                        "PHARMACY",
                        "22.10",
                        "2024-01-17"});
            table21.AddRow(new string[] {
                        "TRN00000006",
                        "ELECTRONICS",
                        "499.00",
                        "2024-01-17"});
            table21.AddRow(new string[] {
                        "TRN00000007",
                        "CLOTHING STORE",
                        "87.50",
                        "2024-01-18"});
            table21.AddRow(new string[] {
                        "TRN00000008",
                        "SUBSCRIPTION",
                        "14.99",
                        "2024-01-18"});
            table21.AddRow(new string[] {
                        "TRN00000009",
                        "UTILITY PAYMENT",
                        "156.00",
                        "2024-01-19"});
            table21.AddRow(new string[] {
                        "TRN00000010",
                        "TRANSFER OUT",
                        "500.00",
                        "2024-01-19"});
            table21.AddRow(new string[] {
                        "TRN00000011",
                        "SALARY DEPOSIT",
                        "3200.00",
                        "2024-01-20"});
            table21.AddRow(new string[] {
                        "TRN00000012",
                        "REFUND",
                        "-25.00",
                        "2024-01-20"});
#line 12
        testRunner.Given("the transaction repository contains the following transactions", ((string)(null)), table21, "Given ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Display first page of transactions")]
        [Xunit.TraitAttribute("FeatureTitle", "Transaction list display with keyset pagination")]
        [Xunit.TraitAttribute("Description", "Display first page of transactions")]
        public void DisplayFirstPageOfTransactions()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Display first page of transactions", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 28
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 11
    this.FeatureBackground();
#line hidden
#line 29
        testRunner.When("I request the first page of transactions", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 30
        testRunner.Then("the transaction list contains 10 transactions", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 31
        testRunner.And("the transaction list indicates a next page exists", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 32
        testRunner.And("the first transaction ID is \"TRN00000001\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Navigate forward to next page")]
        [Xunit.TraitAttribute("FeatureTitle", "Transaction list display with keyset pagination")]
        [Xunit.TraitAttribute("Description", "Navigate forward to next page")]
        public void NavigateForwardToNextPage()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Navigate forward to next page", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 35
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 11
    this.FeatureBackground();
#line hidden
#line 36
        testRunner.When("I request the first page of transactions", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 37
        testRunner.And("I request the next page using the last transaction ID as cursor", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 38
        testRunner.Then("the transaction list contains 2 transactions", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 39
        testRunner.And("the transaction list indicates no next page exists", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Filter by starting transaction ID")]
        [Xunit.TraitAttribute("FeatureTitle", "Transaction list display with keyset pagination")]
        [Xunit.TraitAttribute("Description", "Filter by starting transaction ID")]
        public void FilterByStartingTransactionID()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Filter by starting transaction ID", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 42
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 11
    this.FeatureBackground();
#line hidden
#line 43
        testRunner.When("I request transactions starting from transaction ID \"TRN00000005\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 44
        testRunner.Then("the transaction list contains 7 transactions", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 45
        testRunner.And("the first transaction ID is \"TRN00000006\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="No transactions found")]
        [Xunit.TraitAttribute("FeatureTitle", "Transaction list display with keyset pagination")]
        [Xunit.TraitAttribute("Description", "No transactions found")]
        public void NoTransactionsFound()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("No transactions found", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 48
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 11
    this.FeatureBackground();
#line hidden
#line 49
        testRunner.Given("the transaction repository is empty", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 50
        testRunner.When("I request the first page of transactions", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 51
        testRunner.Then("the transaction list contains 0 transactions", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 52
        testRunner.And("the transaction list indicates no next page exists", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Page size is fixed at 10 records")]
        [Xunit.TraitAttribute("FeatureTitle", "Transaction list display with keyset pagination")]
        [Xunit.TraitAttribute("Description", "Page size is fixed at 10 records")]
        public void PageSizeIsFixedAt10Records()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Page size is fixed at 10 records", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 55
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 11
    this.FeatureBackground();
#line hidden
#line 56
        testRunner.When("I request the first page of transactions", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 57
        testRunner.Then("the transaction list contains exactly 10 transactions", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                TransactionListDisplayWithKeysetPaginationFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                TransactionListDisplayWithKeysetPaginationFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
