// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace NordKredit.BDD.Features.Transactions
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "BDD")]
    [Xunit.TraitAttribute("Category", "Transactions")]
    [Xunit.TraitAttribute("Category", "TRN-BR-004")]
    public partial class DailyBatchCardAndAccountVerificationFeature : object, Xunit.IClassFixture<DailyBatchCardAndAccountVerificationFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "BDD",
                "Transactions",
                "TRN-BR-004"};
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "TransactionVerification.feature"
#line hidden
        
        public DailyBatchCardAndAccountVerificationFeature(DailyBatchCardAndAccountVerificationFeature.FixtureData fixtureData, NordKredit_BDD_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Transactions", "Daily batch card and account verification", @"    As the batch processing system
    I want to verify each daily transaction's card and account before posting
    So that only transactions with valid cards and accounts proceed to posting

    COBOL source: CBTRN01C.cbl:154-251 (daily batch card verification step 1 of 3).
    Business rules: TRN-BR-004 (daily batch card verification).
    Regulations: PSD2 Art.97 (transaction authorization), FFFS 2014:5 Ch.4 S3
                 (operational risk), AML/KYC (source verification).", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="All transactions verified successfully")]
        [Xunit.TraitAttribute("FeatureTitle", "Daily batch card and account verification")]
        [Xunit.TraitAttribute("Description", "All transactions verified successfully")]
        public void AllTransactionsVerifiedSuccessfully()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("All transactions verified successfully", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 13
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table39 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "CardNumber",
                            "TypeCode",
                            "CategoryCode",
                            "Amount",
                            "Description"});
                table39.AddRow(new string[] {
                            "DTX00000001",
                            "4000123456789012",
                            "SA",
                            "5010",
                            "100.00",
                            "GROCERY STORE"});
                table39.AddRow(new string[] {
                            "DTX00000002",
                            "4000123456789099",
                            "SA",
                            "5020",
                            "50.00",
                            "GAS STATION"});
#line 14
        testRunner.Given("the daily transaction repository contains", ((string)(null)), table39, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table40 = new TechTalk.SpecFlow.Table(new string[] {
                            "CardNumber",
                            "AccountId",
                            "CustomerId"});
                table40.AddRow(new string[] {
                            "4000123456789012",
                            "12345678901",
                            "1001"});
                table40.AddRow(new string[] {
                            "4000123456789099",
                            "12345678901",
                            "1001"});
#line 18
        testRunner.And("the card cross-reference file contains", ((string)(null)), table40, "And ");
#line hidden
                TechTalk.SpecFlow.Table table41 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "CurrentBalance"});
                table41.AddRow(new string[] {
                            "12345678901",
                            "5000.00"});
#line 22
        testRunner.And("the account repository contains", ((string)(null)), table41, "And ");
#line hidden
#line 25
        testRunner.When("I run the daily card verification", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 26
        testRunner.Then("all 2 transactions are verified", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 27
        testRunner.And("the verified transaction for \"DTX00000001\" has account ID \"12345678901\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Transaction fails verification when card not in cross-reference")]
        [Xunit.TraitAttribute("FeatureTitle", "Daily batch card and account verification")]
        [Xunit.TraitAttribute("Description", "Transaction fails verification when card not in cross-reference")]
        public void TransactionFailsVerificationWhenCardNotInCross_Reference()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Transaction fails verification when card not in cross-reference", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 30
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table42 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "CardNumber",
                            "TypeCode",
                            "CategoryCode",
                            "Amount",
                            "Description"});
                table42.AddRow(new string[] {
                            "DTX00000003",
                            "9999999999999999",
                            "SA",
                            "5010",
                            "75.00",
                            "UNKNOWN CARD"});
#line 31
        testRunner.Given("the daily transaction repository contains", ((string)(null)), table42, "Given ");
#line hidden
#line 34
        testRunner.And("the card cross-reference file is empty", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 35
        testRunner.And("the account repository is empty", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 36
        testRunner.When("I run the daily card verification", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 37
        testRunner.Then("0 transactions are verified", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 38
        testRunner.And("the verification failure reason for \"DTX00000003\" is \"Card number could not be ve" +
                        "rified\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Transaction fails verification when account not found")]
        [Xunit.TraitAttribute("FeatureTitle", "Daily batch card and account verification")]
        [Xunit.TraitAttribute("Description", "Transaction fails verification when account not found")]
        public void TransactionFailsVerificationWhenAccountNotFound()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Transaction fails verification when account not found", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 41
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table43 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "CardNumber",
                            "TypeCode",
                            "CategoryCode",
                            "Amount",
                            "Description"});
                table43.AddRow(new string[] {
                            "DTX00000004",
                            "4000123456789012",
                            "SA",
                            "5010",
                            "200.00",
                            "MISSING ACCT"});
#line 42
        testRunner.Given("the daily transaction repository contains", ((string)(null)), table43, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table44 = new TechTalk.SpecFlow.Table(new string[] {
                            "CardNumber",
                            "AccountId",
                            "CustomerId"});
                table44.AddRow(new string[] {
                            "4000123456789012",
                            "99999999999",
                            "1001"});
#line 45
        testRunner.And("the card cross-reference file contains", ((string)(null)), table44, "And ");
#line hidden
#line 48
        testRunner.And("the account repository is empty", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 49
        testRunner.When("I run the daily card verification", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 50
        testRunner.Then("0 transactions are verified", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 51
        testRunner.And("the verification failure reason for \"DTX00000004\" is \"Account not found\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Mixed batch with verified and failed transactions")]
        [Xunit.TraitAttribute("FeatureTitle", "Daily batch card and account verification")]
        [Xunit.TraitAttribute("Description", "Mixed batch with verified and failed transactions")]
        public void MixedBatchWithVerifiedAndFailedTransactions()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Mixed batch with verified and failed transactions", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 54
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table45 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "CardNumber",
                            "TypeCode",
                            "CategoryCode",
                            "Amount",
                            "Description"});
                table45.AddRow(new string[] {
                            "DTX00000005",
                            "4000123456789012",
                            "SA",
                            "5010",
                            "100.00",
                            "VALID TXN"});
                table45.AddRow(new string[] {
                            "DTX00000006",
                            "8888888888888888",
                            "SA",
                            "5020",
                            "50.00",
                            "INVALID CARD"});
#line 55
        testRunner.Given("the daily transaction repository contains", ((string)(null)), table45, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table46 = new TechTalk.SpecFlow.Table(new string[] {
                            "CardNumber",
                            "AccountId",
                            "CustomerId"});
                table46.AddRow(new string[] {
                            "4000123456789012",
                            "12345678901",
                            "1001"});
#line 59
        testRunner.And("the card cross-reference file contains", ((string)(null)), table46, "And ");
#line hidden
                TechTalk.SpecFlow.Table table47 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "CurrentBalance"});
                table47.AddRow(new string[] {
                            "12345678901",
                            "5000.00"});
#line 62
        testRunner.And("the account repository contains", ((string)(null)), table47, "And ");
#line hidden
#line 65
        testRunner.When("I run the daily card verification", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 66
        testRunner.Then("1 transaction is verified", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 67
        testRunner.And("1 transaction failed verification", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Empty batch produces no results")]
        [Xunit.TraitAttribute("FeatureTitle", "Daily batch card and account verification")]
        [Xunit.TraitAttribute("Description", "Empty batch produces no results")]
        public void EmptyBatchProducesNoResults()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Empty batch produces no results", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 70
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 71
        testRunner.Given("the daily transaction repository is empty", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 72
        testRunner.When("I run the daily card verification", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 73
        testRunner.Then("all 0 transactions are verified", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                DailyBatchCardAndAccountVerificationFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                DailyBatchCardAndAccountVerificationFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
