// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace NordKredit.BDD.Features.Transactions
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "BDD")]
    [Xunit.TraitAttribute("Category", "Transactions")]
    [Xunit.TraitAttribute("Category", "TRN-BR-005")]
    public partial class DailyBatchTransactionPostingWithBalanceUpdatesFeature : object, Xunit.IClassFixture<DailyBatchTransactionPostingWithBalanceUpdatesFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "BDD",
                "Transactions",
                "TRN-BR-005"};
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "TransactionPosting.feature"
#line hidden
        
        public DailyBatchTransactionPostingWithBalanceUpdatesFeature(DailyBatchTransactionPostingWithBalanceUpdatesFeature.FixtureData fixtureData, NordKredit_BDD_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Transactions", "Daily batch transaction posting with balance updates", @"    As the batch processing system
    I want to post verified transactions updating category and account balances atomically
    So that financial records are accurate and consistent

    COBOL source: CBTRN02C.cbl:193-579 (daily batch transaction posting step 2 of 3).
    Business rules: TRN-BR-005 (daily batch transaction posting).
    Regulations: FFFS 2014:5 Ch.3 (accurate records), FFFS 2014:5 Ch.16 (financial reporting),
                 PSD2 Art.94 (retention).", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Successful posting of a single credit transaction")]
        [Xunit.TraitAttribute("FeatureTitle", "Daily batch transaction posting with balance updates")]
        [Xunit.TraitAttribute("Description", "Successful posting of a single credit transaction")]
        public void SuccessfulPostingOfASingleCreditTransaction()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Successful posting of a single credit transaction", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 13
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "CardNumber",
                            "TypeCode",
                            "CategoryCode",
                            "Amount",
                            "AccountId"});
                table22.AddRow(new string[] {
                            "DTX00000001",
                            "4000123456789012",
                            "SA",
                            "5010",
                            "100.00",
                            "12345678901"});
#line 14
        testRunner.Given("a verified transaction exists", ((string)(null)), table22, "Given ");
#line hidden
#line 17
        testRunner.And("the account \"12345678901\" has balance 5000.00 and cycle credit 0.00 and cycle deb" +
                        "it 0.00", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 18
        testRunner.When("I post the validated transactions", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 19
        testRunner.Then("the posting result shows 1 posted and 0 skipped and 0 failed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 20
        testRunner.And("the account \"12345678901\" has balance 5100.00", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 21
        testRunner.And("the account \"12345678901\" has cycle credit 100.00", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 22
        testRunner.And("the account \"12345678901\" has cycle debit 0.00", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Successful posting of a debit transaction")]
        [Xunit.TraitAttribute("FeatureTitle", "Daily batch transaction posting with balance updates")]
        [Xunit.TraitAttribute("Description", "Successful posting of a debit transaction")]
        public void SuccessfulPostingOfADebitTransaction()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Successful posting of a debit transaction", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 25
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "CardNumber",
                            "TypeCode",
                            "CategoryCode",
                            "Amount",
                            "AccountId"});
                table23.AddRow(new string[] {
                            "DTX00000002",
                            "4000123456789012",
                            "SA",
                            "5020",
                            "-75.00",
                            "12345678901"});
#line 26
        testRunner.Given("a verified transaction exists", ((string)(null)), table23, "Given ");
#line hidden
#line 29
        testRunner.And("the account \"12345678901\" has balance 5000.00 and cycle credit 0.00 and cycle deb" +
                        "it 0.00", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 30
        testRunner.When("I post the validated transactions", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 31
        testRunner.Then("the posting result shows 1 posted and 0 skipped and 0 failed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 32
        testRunner.And("the account \"12345678901\" has balance 4925.00", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 33
        testRunner.And("the account \"12345678901\" has cycle credit 0.00", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 34
        testRunner.And("the account \"12345678901\" has cycle debit 75.00", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Category balance created for new type-category combination")]
        [Xunit.TraitAttribute("FeatureTitle", "Daily batch transaction posting with balance updates")]
        [Xunit.TraitAttribute("Description", "Category balance created for new type-category combination")]
        public void CategoryBalanceCreatedForNewType_CategoryCombination()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Category balance created for new type-category combination", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 37
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "CardNumber",
                            "TypeCode",
                            "CategoryCode",
                            "Amount",
                            "AccountId"});
                table24.AddRow(new string[] {
                            "DTX00000003",
                            "4000123456789012",
                            "SA",
                            "5010",
                            "200.00",
                            "12345678901"});
#line 38
        testRunner.Given("a verified transaction exists", ((string)(null)), table24, "Given ");
#line hidden
#line 41
        testRunner.And("the account \"12345678901\" has balance 1000.00 and cycle credit 0.00 and cycle deb" +
                        "it 0.00", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 42
        testRunner.And("no category balance exists for account \"12345678901\" type \"SA\" category 5010", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 43
        testRunner.When("I post the validated transactions", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 44
        testRunner.Then("the category balance for account \"12345678901\" type \"SA\" category 5010 is 200.00", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Category balance updated for existing type-category combination")]
        [Xunit.TraitAttribute("FeatureTitle", "Daily batch transaction posting with balance updates")]
        [Xunit.TraitAttribute("Description", "Category balance updated for existing type-category combination")]
        public void CategoryBalanceUpdatedForExistingType_CategoryCombination()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Category balance updated for existing type-category combination", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 47
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table25 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "CardNumber",
                            "TypeCode",
                            "CategoryCode",
                            "Amount",
                            "AccountId"});
                table25.AddRow(new string[] {
                            "DTX00000004",
                            "4000123456789012",
                            "SA",
                            "5010",
                            "150.00",
                            "12345678901"});
#line 48
        testRunner.Given("a verified transaction exists", ((string)(null)), table25, "Given ");
#line hidden
#line 51
        testRunner.And("the account \"12345678901\" has balance 1000.00 and cycle credit 0.00 and cycle deb" +
                        "it 0.00", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 52
        testRunner.And("the category balance for account \"12345678901\" type \"SA\" category 5010 is 300.00", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 53
        testRunner.When("I post the validated transactions", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 54
        testRunner.Then("the category balance for account \"12345678901\" type \"SA\" category 5010 is 450.00", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Invalid transactions skipped during posting")]
        [Xunit.TraitAttribute("FeatureTitle", "Daily batch transaction posting with balance updates")]
        [Xunit.TraitAttribute("Description", "Invalid transactions skipped during posting")]
        public void InvalidTransactionsSkippedDuringPosting()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Invalid transactions skipped during posting", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 57
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table26 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "CardNumber",
                            "TypeCode",
                            "CategoryCode",
                            "Amount",
                            "AccountId"});
                table26.AddRow(new string[] {
                            "DTX00000005",
                            "4000123456789012",
                            "SA",
                            "5010",
                            "50.00",
                            "12345678901"});
#line 58
        testRunner.Given("an invalid validated transaction exists", ((string)(null)), table26, "Given ");
#line hidden
#line 61
        testRunner.When("I post the validated transactions", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 62
        testRunner.Then("the posting result shows 0 posted and 1 skipped and 0 failed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Batch posting of multiple transactions")]
        [Xunit.TraitAttribute("FeatureTitle", "Daily batch transaction posting with balance updates")]
        [Xunit.TraitAttribute("Description", "Batch posting of multiple transactions")]
        public void BatchPostingOfMultipleTransactions()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Batch posting of multiple transactions", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 65
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table27 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "CardNumber",
                            "TypeCode",
                            "CategoryCode",
                            "Amount",
                            "AccountId"});
                table27.AddRow(new string[] {
                            "DTX00000006",
                            "4000123456789012",
                            "SA",
                            "5010",
                            "100.00",
                            "12345678901"});
#line 66
        testRunner.Given("a verified transaction exists", ((string)(null)), table27, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table28 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "CardNumber",
                            "TypeCode",
                            "CategoryCode",
                            "Amount",
                            "AccountId"});
                table28.AddRow(new string[] {
                            "DTX00000007",
                            "4000123456789012",
                            "SA",
                            "5020",
                            "-30.00",
                            "12345678901"});
#line 69
        testRunner.And("a verified transaction exists", ((string)(null)), table28, "And ");
#line hidden
#line 72
        testRunner.And("the account \"12345678901\" has balance 2000.00 and cycle credit 0.00 and cycle deb" +
                        "it 0.00", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 73
        testRunner.When("I post the validated transactions", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 74
        testRunner.Then("the posting result shows 2 posted and 0 skipped and 0 failed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 75
        testRunner.And("the account \"12345678901\" has balance 2070.00", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                DailyBatchTransactionPostingWithBalanceUpdatesFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                DailyBatchTransactionPostingWithBalanceUpdatesFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
