// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace NordKredit.BDD.Features.Transactions
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "BDD")]
    [Xunit.TraitAttribute("Category", "Transactions")]
    [Xunit.TraitAttribute("Category", "TRN-BR-006")]
    public partial class DailyTransactionDetailReportGenerationFeature : object, Xunit.IClassFixture<DailyTransactionDetailReportGenerationFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "BDD",
                "Transactions",
                "TRN-BR-006"};
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "TransactionReporting.feature"
#line hidden
        
        public DailyTransactionDetailReportGenerationFeature(DailyTransactionDetailReportGenerationFeature.FixtureData fixtureData, NordKredit_BDD_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/Transactions", "Daily transaction detail report generation", @"    As the batch processing system
    I want to generate a daily transaction detail report with page and account totals
    So that financial reporting requirements are met

    COBOL source: CBTRN03C.cbl:158-374 (daily transaction detail report step 3 of 3).
    Business rules: TRN-BR-006 (daily transaction detail report).
    Regulations: FFFS 2014:5 Ch.7 (financial reporting), PSD2 Art.94 (accessibility),
                 AML 2017:11 Para.3 (monitoring).", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 12
    #line hidden
            TechTalk.SpecFlow.Table table29 = new TechTalk.SpecFlow.Table(new string[] {
                        "TypeCode",
                        "Description"});
            table29.AddRow(new string[] {
                        "SA",
                        "Sales"});
            table29.AddRow(new string[] {
                        "RF",
                        "Refund"});
#line 13
        testRunner.Given("the transaction type lookup contains", ((string)(null)), table29, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table30 = new TechTalk.SpecFlow.Table(new string[] {
                        "TypeCode",
                        "CategoryCode",
                        "Description"});
            table30.AddRow(new string[] {
                        "SA",
                        "5010",
                        "Grocery"});
            table30.AddRow(new string[] {
                        "SA",
                        "5020",
                        "Fuel"});
            table30.AddRow(new string[] {
                        "RF",
                        "5010",
                        "Grocery Return"});
#line 17
        testRunner.And("the transaction category lookup contains", ((string)(null)), table30, "And ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Generate report for single card with multiple transactions")]
        [Xunit.TraitAttribute("FeatureTitle", "Daily transaction detail report generation")]
        [Xunit.TraitAttribute("Description", "Generate report for single card with multiple transactions")]
        public void GenerateReportForSingleCardWithMultipleTransactions()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Generate report for single card with multiple transactions", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 24
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 12
    this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table31 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "CardNumber",
                            "TypeCode",
                            "CategoryCode",
                            "Amount",
                            "OriginationTimestamp"});
                table31.AddRow(new string[] {
                            "TRN00000001",
                            "4000123456789012",
                            "SA",
                            "5010",
                            "100.00",
                            "2024-01-15"});
                table31.AddRow(new string[] {
                            "TRN00000002",
                            "4000123456789012",
                            "SA",
                            "5020",
                            "50.00",
                            "2024-01-15"});
#line 25
        testRunner.Given("the posted transaction repository contains", ((string)(null)), table31, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table32 = new TechTalk.SpecFlow.Table(new string[] {
                            "CardNumber",
                            "AccountId",
                            "CustomerId"});
                table32.AddRow(new string[] {
                            "4000123456789012",
                            "12345678901",
                            "1001"});
#line 29
        testRunner.And("the card cross-reference lookup contains", ((string)(null)), table32, "And ");
#line hidden
#line 32
        testRunner.When("I generate the daily report for date range \"2024-01-15\" to \"2024-01-15\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 33
        testRunner.Then("the report contains 2 detail lines", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 34
        testRunner.And("the report grand total is 150.00", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 35
        testRunner.And("the report has 1 account group", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 36
        testRunner.And("the account total for card \"4000123456789012\" is 150.00", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Report groups transactions by card number with account totals")]
        [Xunit.TraitAttribute("FeatureTitle", "Daily transaction detail report generation")]
        [Xunit.TraitAttribute("Description", "Report groups transactions by card number with account totals")]
        public void ReportGroupsTransactionsByCardNumberWithAccountTotals()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Report groups transactions by card number with account totals", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 39
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 12
    this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table33 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "CardNumber",
                            "TypeCode",
                            "CategoryCode",
                            "Amount",
                            "OriginationTimestamp"});
                table33.AddRow(new string[] {
                            "TRN00000003",
                            "4000123456789012",
                            "SA",
                            "5010",
                            "100.00",
                            "2024-01-15"});
                table33.AddRow(new string[] {
                            "TRN00000004",
                            "4000123456789099",
                            "SA",
                            "5020",
                            "75.00",
                            "2024-01-15"});
#line 40
        testRunner.Given("the posted transaction repository contains", ((string)(null)), table33, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table34 = new TechTalk.SpecFlow.Table(new string[] {
                            "CardNumber",
                            "AccountId",
                            "CustomerId"});
                table34.AddRow(new string[] {
                            "4000123456789012",
                            "12345678901",
                            "1001"});
                table34.AddRow(new string[] {
                            "4000123456789099",
                            "99999999999",
                            "1002"});
#line 44
        testRunner.And("the card cross-reference lookup contains", ((string)(null)), table34, "And ");
#line hidden
#line 48
        testRunner.When("I generate the daily report for date range \"2024-01-15\" to \"2024-01-15\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 49
        testRunner.Then("the report has 2 account groups", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 50
        testRunner.And("the account total for card \"4000123456789012\" is 100.00", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 51
        testRunner.And("the account total for card \"4000123456789099\" is 75.00", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 52
        testRunner.And("the report grand total is 175.00", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Page totals generated every 20 lines")]
        [Xunit.TraitAttribute("FeatureTitle", "Daily transaction detail report generation")]
        [Xunit.TraitAttribute("Description", "Page totals generated every 20 lines")]
        public void PageTotalsGeneratedEvery20Lines()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Page totals generated every 20 lines", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 55
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 12
    this.FeatureBackground();
#line hidden
#line 56
        testRunner.Given("the posted transaction repository contains 25 transactions for card \"400012345678" +
                        "9012\" with amount 10.00 each on \"2024-01-15\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table35 = new TechTalk.SpecFlow.Table(new string[] {
                            "CardNumber",
                            "AccountId",
                            "CustomerId"});
                table35.AddRow(new string[] {
                            "4000123456789012",
                            "12345678901",
                            "1001"});
#line 57
        testRunner.And("the card cross-reference lookup contains", ((string)(null)), table35, "And ");
#line hidden
#line 60
        testRunner.When("I generate the daily report for date range \"2024-01-15\" to \"2024-01-15\" with page" +
                        " size 20", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 61
        testRunner.Then("the report contains 25 detail lines", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 62
        testRunner.And("the report has 2 page totals", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 63
        testRunner.And("page total 1 is 200.00", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 64
        testRunner.And("page total 2 is 50.00", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Report lines enriched with type and category descriptions")]
        [Xunit.TraitAttribute("FeatureTitle", "Daily transaction detail report generation")]
        [Xunit.TraitAttribute("Description", "Report lines enriched with type and category descriptions")]
        public void ReportLinesEnrichedWithTypeAndCategoryDescriptions()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Report lines enriched with type and category descriptions", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 67
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 12
    this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table36 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "CardNumber",
                            "TypeCode",
                            "CategoryCode",
                            "Amount",
                            "OriginationTimestamp"});
                table36.AddRow(new string[] {
                            "TRN00000030",
                            "4000123456789012",
                            "SA",
                            "5010",
                            "42.50",
                            "2024-01-15"});
#line 68
        testRunner.Given("the posted transaction repository contains", ((string)(null)), table36, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table37 = new TechTalk.SpecFlow.Table(new string[] {
                            "CardNumber",
                            "AccountId",
                            "CustomerId"});
                table37.AddRow(new string[] {
                            "4000123456789012",
                            "12345678901",
                            "1001"});
#line 71
        testRunner.And("the card cross-reference lookup contains", ((string)(null)), table37, "And ");
#line hidden
#line 74
        testRunner.When("I generate the daily report for date range \"2024-01-15\" to \"2024-01-15\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 75
        testRunner.Then("report line 1 has type description \"SA-Sales\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 76
        testRunner.And("report line 1 has category description \"5010-Grocery\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Empty report for date range with no transactions")]
        [Xunit.TraitAttribute("FeatureTitle", "Daily transaction detail report generation")]
        [Xunit.TraitAttribute("Description", "Empty report for date range with no transactions")]
        public void EmptyReportForDateRangeWithNoTransactions()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Empty report for date range with no transactions", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 79
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 12
    this.FeatureBackground();
#line hidden
#line 80
        testRunner.When("I generate the daily report for date range \"2099-01-01\" to \"2099-01-31\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 81
        testRunner.Then("the report contains 0 detail lines", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 82
        testRunner.And("the report grand total is 0.00", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 83
        testRunner.And("the report has 0 account groups", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Report generation fails when card cross-reference missing")]
        [Xunit.TraitAttribute("FeatureTitle", "Daily transaction detail report generation")]
        [Xunit.TraitAttribute("Description", "Report generation fails when card cross-reference missing")]
        public void ReportGenerationFailsWhenCardCross_ReferenceMissing()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Report generation fails when card cross-reference missing", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 86
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 12
    this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table38 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "CardNumber",
                            "TypeCode",
                            "CategoryCode",
                            "Amount",
                            "OriginationTimestamp"});
                table38.AddRow(new string[] {
                            "TRN00000031",
                            "9999999999999999",
                            "SA",
                            "5010",
                            "10.00",
                            "2024-01-15"});
#line 87
        testRunner.Given("the posted transaction repository contains", ((string)(null)), table38, "Given ");
#line hidden
#line 90
        testRunner.When("I generate the daily report for date range \"2024-01-15\" to \"2024-01-15\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 91
        testRunner.Then("the report generation fails with a data integrity error", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                DailyTransactionDetailReportGenerationFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                DailyTransactionDetailReportGenerationFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
